"""new fields on user model

Revision ID: 093bd20acadc
Revises: d5e2bd55456b
Create Date: 2024-02-12 11:15:16.174668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093bd20acadc'
down_revision = 'd5e2bd55456b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
